# Generated by Django 5.0 on 2025-10-29 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(limit_choices_to={'role': 'TRAINER'}, related_name='trainer_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
